frontend/common/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, current_app
from frontend.common.forms import RegistrationForm, LoginForm
from flask_login import login_user, current_user, logout_user
import requests
from frontend.models import User
from frontend import db

common = Blueprint('common', __name__)


# View Function - User Registration
@common.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('dash.dashboard'))
    form = RegistrationForm()
    print(form.confirm_password.data)
    if form.validate_on_submit():
        request_response = requests.post(current_app.config['ENDPOINT_ROUTE'] + current_app.config['NORMAL_REGISTER_URL'],
                                         json = {
                                             'name': form.name.data,
                                             'password': form.password.data,
                                             'email': form.email.data
                                         })
        response = request_response.json()
        if response['status'] == 1:
            flash(f'Account created for {form.name.data}.', 'success')
            return redirect(url_for('common.login'))
        else:
            flash(response['error'], 'danger')
    return render_template('register.html', title='Register', form=form)


# View Function - User Login
@common.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('dash.dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        request_response = requests.post(current_app.config['ENDPOINT_ROUTE'] + current_app.config['LOGIN_URL'],
                                         json={
                                             'email': form.email.data,
                                             'password': form.password.data,
                                         })
        response = request_response.json()
        if response['status'] == 1:
            user = User(response['id'], response['name'], response['email'], response['auth_token'])
            db.session.add(user)
            db.session.commit()
            print(User.query.filter_by(user_id=response['id']).order_by(User.id.desc()).first().auth_token)
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('dash.dashboard'))
        else:
            flash(response['error'], 'danger')
    return render_template('login.html', title='Login', form=form)


# View Function - User Logout
@common.route('/logout', methods=['GET'])
def logout():
    logout_user()
    flash("User Logged Out Successfully", 'success')
    return redirect(url_for('common.login'))

frontend/templates/index.html
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="static/spindler-logo-transparent.png">
    <!-- Author Meta -->
    <meta name="author" content="codepixer">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Courses</title>

    <!--
            Google Font
            ============================================= -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,500,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500i" rel="stylesheet">

    <!--
            CSS
            ============================================= -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/themify-icons/0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="static/main/css/linearicons.css">
    <link rel="stylesheet" href="static/main/css/font-awesome.min.css">
    <link rel="stylesheet" href="static/main/css/bootstrap.css">
    <link rel="stylesheet" href="static/main/css/magnific-popup.css">
    <link rel="stylesheet" href="static/main/css/nice-select.css">
    <link rel="stylesheet" href="static/main/css/animate.min.css">
    <link rel="stylesheet" href="static/main/css/owl.carousel.css">
    <link rel="stylesheet" href="static/main/css/main.css">

    <!-- Card View -->
    <link rel="stylesheet" href="static/card/css/style.css">
</head>

<body>

<!-- Start Header Area -->
<header id="header">
    <div class="container">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a href="/"><img src="static/main/img/logo.png" alt="" title="" style="height:40px"/></a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li class="menu-active"><a href="/">Home</a></li>
                    {% if not login_info['status'] %}
                        <li class="menu-has-children"><a href="{{ url_for('common.login') }}">Login</a></li>
                        <li class="menu-has-children"><a href="{{ url_for('common.register') }}">Register</a></li>
                    {% else %}
                        <li class="menu-has-children"><a href="">{{ login_info['name'] }}</a>
                            <ul>
                                <li><a href="{{ url_for('dash.dashboard') }}">Dashboard</a></li>
                                <li><a href="{{ url_for('common.logout') }}">Logout</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
            </nav><!-- #nav-menu-container -->
        </div>
    </div>
</header>
<!-- End Header Area -->


<!-- Start Banner Area -->
<section class="home-banner-area relative">
    <div class="container">
        <div class="row fullscreen d-flex align-items-center justify-content-center">
            <div class="banner-content col-lg-8 col-md-12">
                <h1 class="wow fadeIn" data-wow-duration="4s">Search for images through <br> NASA's database</h1>
                <p class="text-white">
                    Explore beyond your imagination!
                </p>

                <div class="input-wrap">
                    <form action="" class="justify-content-between">
                        <div class="d-flex">
                            <input type="text" placeholder="Search Universe" class="form-control" name="q"
                                   required>
                            <button type="submit" class="btn search-btn">Search</button>
                            <button type="button" class="btn search-btn" onclick="showHideExtras()">Advanced</button>
                        </div>
                        <br>
                        <div id="extras" style="display:none">
                            <div class="row">
                                <div class="col-lg-4">
                                    <input type="text" placeholder="Center Code" class="form-control" name="center">
                                </div>
                                <div class="col-lg-8">
                                    <input type="text" placeholder="Location" class="form-control" name="location">
                                </div>
                            </div>
                            <div class="row mt-10">
                                <div class="col-lg-6">
                                    <input type="text" placeholder="Keywords" class="form-control" name="keywords">
                                </div>
                                <div class="col-lg-3">
                                    <input type="text" placeholder="Start Year" class="form-control" name="start-year">
                                </div>
                                <div class="col-lg-3">
                                    <input type="text" placeholder="End Year" class="form-control" name="end-year">
                                </div>
                            </div>
                            <div class="row mt-10">
                                <div class="col-lg-6">
                                    <input type="text" placeholder="NASA ID" class="form-control" name="nasa-id">
                                </div>
                                <div class="col-lg-6">
                                    <input type="text" placeholder="Photographer" class="form-control"
                                           name="photographer">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <h4 class="text-white">Top searches</h4>

                <div class="courses pt-20">
                    {% for i in range(searches[:7]|length) %}
                        <a href="?q={{ searches[i][1] | replace(' ', '+') }}" data-wow-duration="1s"
                           data-wow-delay="{{ (i + 1) * 0.3 }}s"
                           class="primary-btn transparent mr-10 mb-10 wow fadeInDown">{{ searches[i][1] }}</a>
                    {% endfor %}
                    {% if searches|length < 7 %}
                        {% for i in range(7 - searches|length) %}
                            <a href="#" data-wow-duration="1s" data-wow-delay="{{ (searches|length + i + 1) * 0.3 }}s"
                               class="primary-btn transparent mr-10 mb-10 wow fadeInDown">Spindler</a>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="rocket-img">
        <img src="static/main/img/rocket.png" alt="">
    </div>
</section>

<script>
    function showHideExtras() {
        var x = document.getElementById('extras');
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }
</script>
<!-- End Banner Area -->


<!-- Start Footer Area -->
<footer class="footer-area section-gap">
    <div class="container">
        <div class="footer-bottom row align-items-center">
            <p class="footer-text m-0 col-lg-8 col-md-12">
                Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                All rights reserved | Spindler is brought to you by Rachit Bhargava
            </p>
        </div>
    </div>
</footer>
<!-- End Footer Area -->

<!-- ####################### Start Scroll to Top Area ####################### -->
<div id="back-top">
    <a title="Go to Top" href="#"></a>
</div>
<!-- ####################### End Scroll to Top Area ####################### -->

<script src="static/main/js/vendor/jquery-2.2.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="static/main/js/vendor/bootstrap.min.js"></script>
<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="static/main/js/easing.min.js"></script>
<script src="static/main/js/hoverIntent.js"></script>
<script src="static/main/js/superfish.min.js"></script>
<script src="static/main/js/jquery.ajaxchimp.min.js"></script>
<script src="static/main/js/jquery.magnific-popup.min.js"></script>
<script src="static/main/js/owl.carousel.min.js"></script>
<script src="static/main/js/owl-carousel-thumb.min.js"></script>
<script src="static/main/js/jquery.sticky.js"></script>
<script src="static/main/js/jquery.nice-select.min.js"></script>
<script src="static/main/js/parallax.min.js"></script>
<script src="static/main/js/waypoints.min.js"></script>
<script src="static/main/js/wow.min.js"></script>
<script src="static/main/js/jquery.counterup.min.js"></script>
<script src="static/main/js/mail-script.js"></script>
<script src="static/main/js/main.js"></script>
</body>

</html>

frontend/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="static/log/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/log/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/log/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/log/fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/log/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="static/log/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/log/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/log/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="static/log/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/log/css/util.css">
	<link rel="stylesheet" type="text/css" href="static/log/css/main.css">
<!--===============================================================================================-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('static/log/images/bg-01.jpg');">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method='POST' action="">
                    {{ form.hidden_tag() }}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-34 p-t-27">
						Log in
					</span>
                    {% with messages = get_flashed_messages(with_categories = true) %}
            	        {% if messages %}
	                        {% for category, message in messages %}
                	            <div class = 'alert alert-{{ category }}'>
	                                {{ message }}
	                            </div>
                            {% endfor %}
	                    {% endif %}
                    {% endwith %}
                    <div class="wrap-input100 validate-input" data-validate = "Enter your GeorgiaTech email address">
                        {{ form.email(class="input100", placeholder="Email address") }}
                        <span class="focus-input100" data-placeholder="&#xf15a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter your password">
						{{ form.password(class="input100", placeholder="Password") }}
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>

					<div class="contact100-form-checkbox">
						{{ form.remember(class="input-checkbox100", id="ckb1", type="checkbox") }}
						<label class="label-checkbox100" for="ckb1">
							Remember me
						</label>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit" id="submit" name="submit">
							Login
						</button>
					</div>
                </form>

                <div class="container-login100-form-btn p-t-10">
                    <a href="/register">
                        <button class="login100-form-btn">
                            Sign Up
                        </button>
                    </a>
                </div>

                <div class="text-center p-t-40">
                    <a class="txt1" href="#">
                        Forgot Password?
                    </a>
                </div>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="static/log/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="static/log/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="static/log/vendor/bootstrap/js/popper.js"></script>
	<script src="static/log/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="static/log/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="static/log/vendor/daterangepicker/moment.min.js"></script>
	<script src="static/log/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="static/log/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="static/log/js/main.js"></script>

</body>
</html>

frontend/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Sign Up</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="static/log/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/log/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/log/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/log/fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/log/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="static/log/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/log/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/log/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="static/log/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/log/css/util.css">
	<link rel="stylesheet" type="text/css" href="static/log/css/main.css">
<!--===============================================================================================-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url('static/log/images/bg-01.jpg');">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method='POST' action="">
                    {{ form.hidden_tag() }}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-34 p-t-27">
						Sign Up
					</span>
                    {% with messages = get_flashed_messages(with_categories = true) %}
            	        {% if messages %}
	                        {% for category, message in messages %}
                	            <div class = 'alert alert-{{ category }}'>
	                                {{ message }}
	                            </div>
                            {% endfor %}
	                    {% endif %}
                    {% endwith %}
                    <div class="wrap-input100 validate-input" data-validate = "Enter your name">
                        {{ form.name(class="input100", placeholder="Full Name") }}
                        <span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>

                    <div class="wrap-input100 validate-input" data-validate = "Enter your GeorgiaTech email address">
                        {{ form.email(class="input100", placeholder="Email address") }}
                        <span class="focus-input100" data-placeholder="&#xf15a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter your password">
						{{ form.password(class="input100", placeholder="Password") }}
						<span class="focus-input100" data-placeholder="&#xf190;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter your password again">
						{{ form.confirm_password(class="input100", placeholder="Confirm Password") }}
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit" id="submit" name="submit">
							Sign Up
						</button>
					</div>
                </form>

                <div class="container-login100-form-btn p-t-10">
                    <a href="/login">
                        <button class="login100-form-btn">
                            Login
                        </button>
                    </a>
                </div>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="static/log/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="static/log/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="static/log/vendor/bootstrap/js/popper.js"></script>
	<script src="static/log/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="static/log/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="static/log/vendor/daterangepicker/moment.min.js"></script>
	<script src="static/log/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="static/log/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="static/log/js/main.js"></script>

</body>
</html>